const bgNames: string[] = [
  "Brass: Birmingham (2018)",
  "Pandemic Legacy: Season 1 (2015)",
  "Gloomhaven (2017)",
  "Ark Nova (2021)",
  "Twilight Imperium: Fourth Edition (2017)",
  "Terraforming Mars (2016)",
  "Dune: Imperium (2020)",
  "Gloomhaven: Jaws of the Lion (2020)",
  "War of the Ring: Second Edition (2011)",
  "Star Wars: Rebellion (2016)",
  "Spirit Island (2017)",
  "Gaia Project (2017)",
  "Twilight Struggle (2005)",
  "Through the Ages: A New Story of Civilization (2015)",
  "Great Western Trail (2016)",
  "The Castles of Burgundy (2011)",
  "Scythe (2016)",
  "7 Wonders Duel (2015)",
  "Eclipse: Second Dawn for the Galaxy (2020)",
  "Brass: Lancashire (2007)",
  "Nemesis (2018)",
  "Clank! Legacy: Acquisitions Incorporated (2019)",
  "A Feast for Odin (2016)",
  "Concordia (2013)",
  "Wingspan (2019)",
  "Terra Mystica (2012)",
  "Arkham Horror: The Card Game (2016)",
  "Lost Ruins of Arnak (2020)",
  "Root (2018)",
  "Great Western Trail: Second Edition (2021)",
  "Orléans (2014)",
  "Everdell (2018)",
  "Mage Knight Board Game (2011)",
  "Barrage (2019)",
  "Viticulture Essential Edition (2015)",
  "The Crew: Mission Deep Sea (2021)",
  "Too Many Bones (2017)",
  "Food Chain Magnate (2015)",
  "Pax Pamir: Second Edition (2019)",
  "Marvel Champions: The Card Game (2019)",
  "Frosthaven (2022)",
  "Underwater Cities (2018)",
  "Puerto Rico (2002)",
  "Caverna: The Cave Farmers (2013)",
  "Cascadia (2021)",
  "Blood Rage (2015)",
  "Anachrony (2017)",
  "On Mars (2020)",
  "Agricola (2007)",
  "Crokinole (1876)",
  "Kanban EV (2020)",
  "Pandemic Legacy: Season 0 (2020)",
  "Sleeping Gods (2021)",
  "Heat: Pedal to the Metal (2022)",
  "Pandemic Legacy: Season 2 (2017)",
  "Mansions of Madness: Second Edition (2016)",
  "Lisboa (2017)",
  "Maracaibo (2019)",
  "Tzolk'in: The Mayan Calendar (2012)",
  "Power Grid (2004)",
  "The Quacks of Quedlinburg (2018)",
  "Clans of Caledonia (2017)",
  "Le Havre (2008)",
  "Paladins of the West Kingdom (2019)",
  "Star Wars: Imperial Assault (2014)",
  "The Crew: The Quest for Planet Nine (2019)",
  "The Gallerist (2015)",
  "Grand Austria Hotel (2015)",
  "Mechs vs. Minions (2016)",
  "Cthulhu: Death May Die (2019)",
  "Android: Netrunner (2012)",
  "Kingdom Death: Monster (2015)",
  "Azul (2017)",
  "Obsession (2018)",
  "Agricola (Revised Edition) (2016)",
];

const bgDescs: string[] = [
  "Build networks, grow industries, and navigate the world of the Industrial Revolution.",
  "Mutating diseases are spreading around the world - can your team save humanity?",
  "Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy!",
  "Plan and build a modern, scientifically managed zoo to support conservation projects.",
  "Build an intergalactic empire through trade, research, conquest and grand politics.",
  "Compete with rival CEOs to make Mars habitable and build your corporate empire.",
  "Influence, intrigue, and combat in the universe of Dune.",
  "Vanquish monsters with strategic cardplay in a 25-scenario Gloomhaven campaign.",
  "The Fellowship and the Free Peoples clash with Sauron over the fate of Middle-Earth.",
  "Strike from your hidden base as the Rebels—or find and destroy it as the Empire.",
  "Island Spirits join forces using elemental powers to defend their home from invaders.",
  "Expand, research, upgrade, and settle the galaxy with one of 14 alien species.",
  "Relive the Cold War and rewrite history in an epic clash between the USA and USSR.",
  "Rewrite history as you build up your civilization in this epic card drafting game!",
  "Use strategic outposts and navigate danger as you herd your cattle to Kansas City.",
  "Plan, trade, and build your Burgundian estate to prosperity and prominence.",
  "Five factions vie for dominance in a war-torn, mech-filled, dieselpunk 1920s Europe.",
  "Science? Military? What will you draft to win this head-to-head version of 7 Wonders?",
  "Build an interstellar civilization by exploration, research, conquest, and diplomacy.",
  "Test your economic mettle as you build and network in the Industrial Revolution.",
  "Survive an alien-infested spaceship, but beware of other players and their agendas!",
  "Go forth, be bold, and ACQUIRE! in this campaign version of Clank!",
  "Puzzle together the life of a Viking village as you hunt, farm, craft, and explore.",
  "Merchants in the Roman Empire compete to amass the greatest amount of wealth.",
  "Attract a beautiful and diverse collection of birds to your wildlife preserve.",
  "Play fantastical factions. Expand your influence by terraforming and joining cults.",
  "Investigate the horrors of Arkham while courting cosmic doom.",
  "Explore an island to find resources and discover the lost ruins of Arnak.",
  "Decide the fate of the forest as woodland factions fight for contrasting goals.",
  "Wrangle your herd of cows across the Midwest prairie and deliver it to Kansas City.",
  "Craftsmen, scholars & monks can help you reign supreme—but who will turn up to help?",
  "Gather resources to develop a harmonious village of woodland critters and structures.",
  "Build your hero’s spells, abilities, and artifacts as you explore & conquer cities.",
  "Nations vie for hydroelectric dominance in a dystopia where water is power.",
  "Create the most prosperous winery in Italy from the Tuscan vineyard you've inherited.",
  "Dive into the deep sea in this co-operative trick-taking game with variable missions.",
  "Toss gobs of unique dice in an epic adventure en route to a final boss showdown.",
  "Strategically hire and manage your workforce to outcompete rival fast food chains.",
  "Swing the tides of The Great Game as countries vie for control of Afghanistan.",
  "Battle Marvel villains with unique teams of iconic heroes in this LCG.",
  "Adventure in the frozen north and build up your outpost throughout an epic campaign.",
  "Develop future cities on the seafloor through politics, production, and science.",
  "Ship goods, construct buildings, and choose roles that benefit you more than others.",
  "From a simple cave, expand your dwarven home through mining, agriculture, and more.",
  "Create the most harmonious ecosystem as you puzzle together habitats and wildlife.",
  "Ragnarök has come! Secure your place in Valhalla in epic Viking battles.",
  "Use Exosuits & time travel to ensure your vision for the future after the cataclysm.",
  "Be a part of the first Martian colony, striving to be the best contributor.",
  "Build your farmstead by sowing fields and raising livestock. But don't forget to eat!",
  "Flick discs and make trick shots in this traditional Canadian dexterity game!",
  "EV-factory workers optimize and innovate to stand out at the big board meeting.",
  "Work together during the Cold War to prevent a Soviet bio-threat.",
  "Voyages of the steamship Manticore and her crew on the Wandering Sea.",
  "Manage your race car's speed to keep from overheating.",
  "The world is a mystery after a devastating pandemic—where will your team go?",
  "Unravel mysteries in Arkham with your investigative team in this app-guided game.",
  "Compete to reconstruct the city of Lisboa after the great earthquake of 1755.",
  "Seafarers journey to obtain wealth and fame in the 17th century Caribbean.",
  "Lead your people, build monuments and make offerings to earn the favour of the gods.",
  "Bid, network, and manage resources in a race to supply the most cities with power.",
  "Pull ingredients from your stock to make your pot bubble, but hopefully not explode!",
  "Lead your unique Scottish clan to economic might via production, trade, and export.",
  "Establish a supply chain by collecting resources, building industries, and shipping.",
  "Invaders are coming from everywhere. Keep the faith and defend your homeland.",
  "Play as Rebel or Imperial forces to fulfill mission objectives.",
  "Go on many planet-discovering space missions in this cooperative trick-taking game.",
  "Amass a fortune, and stake your reputation by operating a lucrative art gallery.",
  "Serve guests and prepare rooms to be the best hotelier in the Viennese modern age.",
  "Cooperatively program and pilot your mechs to defeat an army of marauding minions.",
  "Disrupt the ritual and slay the Elder Gods in this co-op dice chucker.",
  "Megacorporation versus Netrunner in this futuristic cyberpunk game of cat and mouse.",
  "Try to survive in a nightmarish world that lies under eternal darkness.",
  "Artfully embellish the walls of your palace by drafting the most beautiful tiles.",
  "Renovate an estate, manage servants, and pursue romance in Victorian England.",
  "Help your farm to prosper in this updated, streamlined edition of the acclaimed game.",
];

export { bgNames, bgDescs };
